[package]
name = "hyper-client-sockets"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "A Hyper client library allowing access to Unix, VSock and Firecracker sockets"
rust-version = "1.63"
repository = "https://github.com/kanpov/hyper-client-sockets"
readme = "README.md"
keywords = ["hyper", "client", "sockets"]
categories = ["web-programming", "web-programming::http-client"]

[dependencies]
hex = "0.4.3"
hyper = { version = "1.4.1", default-features = false }
pin-project-lite = "0.2.14"
futures-io = "0.3.31"
http = "1.1.0"

# hyper-util support
tower-service = { version = "0.3.3", optional = true }
hyper-util = { version = "0.1.9", features = [
    "client-legacy",
], optional = true }
# tokio backend
tokio = { version = "1.40.0", features = ["net", "io-util"], optional = true }
tokio-vsock = { version = "0.6.0", optional = true }
tokio-util = { version = "0.7.12", default-features = false, optional = true, features = [
    "compat",
] }
# async-io backend
async-io = { version = "2.0.0", optional = true }
vsock = { version = "0.5.1", optional = true }
smol-hyper = { version = "0.1.1", default-features = false, features = [
    "async-io",
], optional = true }
# firecracker
futures-util = { version = "0.3.31", default-features = false, features = [
    "io",
], optional = true }

[dev-dependencies]
http-body-util = "0.1.2"
hyper-util = { version = "0.1.6", features = ["http1"] }
hyper-client-sockets = { path = ".", features = ["full"] }
tokio = { version = "1.38.0", features = ["macros", "fs"] }
hyper = { version = "1.4.1", features = ["server"] }
uuid = { version = "1.10.0", features = ["v4"] }
bytes = "1.7.2"
rand = "0.8.5"

[features]
default = []
full = [
    "tokio-backend",
    "async-io-backend",
    "unix",
    "vsock",
    "firecracker",
    "connector",
]
tokio-backend = [
    "dep:tokio",
    "dep:tokio-vsock",
    "hyper-util/tokio",
    "dep:tokio-util",
]
async-io-backend = ["dep:async-io", "dep:vsock", "dep:smol-hyper"]
connector = ["dep:tower-service", "dep:hyper-util"]
unix = []
vsock = []
firecracker = ["dep:futures-util"]
