[package]
name = "hyper-client-sockets"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "A Hyper client library allowing access to Unix, VSock and Firecracker sockets"
rust-version = "1.63"
repository = "https://github.com/kanpov/hyper-client-sockets"
readme = "README.md"
keywords = ["hyper", "client", "sockets"]
categories = ["web-programming", "web-programming::http-client"]

[dependencies]
hex = "0.4.3"
hyper = { version = "1.4.1", features = ["client"] }
hyper-util = { version = "0.1.9", features = ["client-legacy", "tokio"] }
pin-project-lite = "0.2.14"
tower-service = "0.3.3"

tokio = { version = "1.40.0", features = ["net", "io-util"], optional = true }
tokio-vsock = { version = "0.6.0", optional = true }

[dev-dependencies]
http-body-util = "0.1.2"
hyper-util = { version = "0.1.6", features = ["http1"] }
hyper-client-sockets = { path = ".", features = [
    "unix",
    "vsock",
    "firecracker",
] }
tokio = { version = "1.38.0", features = ["macros", "fs"] }
hyper = { version = "1.4.1", features = ["server"] }
uuid = { version = "1.10.0", features = ["v4"] }
bytes = "1.7.2"
rand = "0.8.5"

[features]
default = []
unix = ["dep:tokio"]
vsock = ["dep:tokio-vsock"]
firecracker = ["dep:tokio"]
